# Generated by Django 2.2.5 on 2020-02-17 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharperatio', models.FloatField(blank=True, default=None, null=True)),
                ('volatility', models.FloatField(blank=True, default=None, null=True)),
                ('expected_return', models.FloatField(blank=True, default=None, null=True)),
                ('momentum', models.FloatField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('analyzed_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Stock')),
            ],
        ),
    ]
